### ISSUE TITLE
stickers and profile banners do not work

### ISSUE THREAD

**Issue by oliver408i** [Shimoro-Rune/NitroPerks#2]
![image](https://user-images.githubusercontent.com/75344601/136867360-53067713-00e2-41ec-b959-978c864f27a7.png)
![image](https://user-images.githubusercontent.com/75344601/136867490-8f9cd801-03b0-474b-85ce-57c53a174f76.png)

**Comment by haqr247** [comment]
has sticker issue been resolved?
