### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by ohitstom** [Shimoro-Rune/NitroPerks#23]
zere plugin lib forced an update and now the patch doesnt work anymore

**Comment by bygalacos** [comment]
You can get fixed version here https://github.com/bygalacos/OnesPluginLibrary/blob/main/0PluginLibrary.plugin.js

**Comment by DaVouz** [comment]
thank you brother i had the same issue

**Comment by GloftOfficial** [comment]
Mine freezes on launch with that library but I guess its a me problem if it works fine for you guys.

**Comment by bygalacos** [comment]
> Mine freezes on launch with that library but I guess its a me problem if it works fine for you guys.

I got these plugins installed
BDFDB
BetterCodeblocks
BetterRoleColors
CallTimeCounter
CrashRecovery
CreationDate
Double Click To Edit
Freemoji (disabled rn)
GuildProfile
MessageLoggerV2
Multi Instance
NitroPerks
PlatformIndicators
PluginRepo
QuickMention
ShowConnections
ShowHiddenChannels
SplitLargeMessages
SpotifyListenAlong
TypingIndicator
TypingUsersAvatars
UnreadCountBadges
UserVolumeBooster
XenoLib
ZeresPluginLibrary (fixed one)

**Comment by bygalacos** [comment]
> Mine freezes on launch with that library but I guess its a me problem if it works fine for you guys.

I got these plugins installed:

- BDFDB
- BetterCodeblocks
- BetterRoleColors
- CallTimeCounter
- CrashRecovery
- CreationDate
- Double Click To Edit
- Freemoji (disabled rn)
- GuildProfile
- MessageLoggerV2
- Multi Instance
- NitroPerks
- PlatformIndicators
- PluginRepo
- QuickMention
- ShowConnections
- ShowHiddenChannels
- SplitLargeMessages
- SpotifyListenAlong
- TypingIndicator
- TypingUsersAvatars
- UnreadCountBadges
- UserVolumeBooster
- XenoLib
- ZeresPluginLibrary (fixed one)

Try CrashRecovery it can fix your problem or tell whats wrong.

**Comment by GloftOfficial** [comment]
Fixed it turns out the plugin [Copier](https://github.com/Strencher/BetterDiscordStuff/blob/master/Copier/Copier.plugin.js) was causing the crash
